// Generated by CoffeeScript 1.3.1

mxUserStyle('cheddar', ".date-show:hover,\n.dropdown:hover,\n.graph_module_container:hover,\ntable:hover {\n  transform: scale(-1, 1);\n  -moz-transform: scale(-1, 1);\n  -webkit-transform: scale(-1, 1);\n}");

mxUserStyle('ofir', "body {\n  -webkit-transform: scale(-1, 1);\n  -moz-transform: scale(-1, 1);\n}");

mxUserStyle('fangjin', "@-webkit-keyframes sway {\n  0%   { -webkit-transform: rotate(-1deg); }\n  100% { -webkit-transform: rotate(1deg); }\n}\n\nbody {\n  -webkit-animation: sway 10s ease-in-out 0s infinite alternate;\n}");

mxUserStyle('xavier', "@-webkit-keyframes move {\n  0%   { -webkit-transform: translate(20px, 20px); }\n  25%  { -webkit-transform: translate(20px, -20px); }\n  50%  { -webkit-transform: translate(-20px, -20px); }\n  75%  { -webkit-transform: translate(-20px, 20px); }\n  100% { -webkit-transform: translate(20px, 20px); }\n}\n\nbody {\n  -webkit-animation: move 10s linear 0s infinite;\n}");

mxUserStyle('nisha', "body {\n  -webkit-transform: rotate(-1deg);\n}");

mxUserStyle('xavier', "@-webkit-keyframes text-blur {\n  0%   {text-shadow: 0 0 0px black; }\n  40%  {text-shadow: 0 0 0px black; }\n  50%  {text-shadow: 0 0 5px black; }\n  60%  {text-shadow: 0 0 5px black; }\n  70%  {text-shadow: 0 0 0px black; }\n  100% {text-shadow: 0 0 0px black; }\n}\n\nbody {\n  -webkit-animation: text-blur 10s linear 0s infinite;\n}");

mxUserStyle('nelson', "@-webkit-keyframes invert {\n   0% {-webkit-filter: invert(0);}\n   89% {-webkit-filter: invert(0);}\n   90% {-webkit-filter: invert(1);}\n   95% {-webkit-filter: invert(1);}\n   100% {-webkit-filter: invert(0);}\n }\n\nhtml {\n  -webkit-animation: invert 10s linear 0s infinite;\n}");

mxUserStyle('gian', "@-webkit-keyframes rotx {\n  0%   { -webkit-transform: rotateX(-7deg); }\n  100% { -webkit-transform: rotateX(7deg); }\n}\n\n.left_cont {\n  -webkit-perspective: 1000;\n}\n\n.graph_module_container {\n  -webkit-transform-origin: left top;\n  -webkit-animation: rotx 4s ease-in-out 0s infinite alternate;\n}");

mxUserStyle('young', "#user_name:before {\n  content: 'Forever ';\n}\n\n@-webkit-keyframes rainbow {\n  0%   { -webkit-filter: hue-rotate(0deg); }\n  100% { -webkit-filter: hue-rotate(360deg); }\n}\n\n#-webkit-web-inspector {\n  -webkit-transform: rotate(180deg);\n}");

mxUserStyle('dipti', "body {\n  -webkit-transform: rotate(1deg);\n}");

mxUserStyle('luca', ".lookup_table.detail.loaded,\n.graph_module_container {\n  -webkit-transform: rotate(180deg);\n}");

mxUserStyle('shuan', "@-webkit-keyframes sway {\n  0%   { -webkit-transform: rotate(-1deg); }\n  100% { -webkit-transform: rotate(1deg); }\n}\n\n.lookup_table.detail.loaded {\n  -webkit-animation: sway 10s ease-in-out 0s infinite alternate;\n}");

mxUserStyle('sam', ".lookup_table.detail.loaded,\n.graph_module_container {\n  -webkit-transform: rotate(180deg);\n}");

mxUserStyle('tom', "* {\n  color: pink !important;\n}\n\ntext {\n  fill: pink;\n}");

mxUserStyle('katherine', "body {\n  font-family: 'Comic Sans MS', cursive !important;\n}");

mxUserStyle('adam', "@-webkit-keyframes rainbow {\n  0%   { -webkit-filter: hue-rotate(0deg); }\n  100% { -webkit-filter: hue-rotate(360deg); }\n}\n\nhtml {\n  -webkit-animation: rainbow 60s infinite;\n}");

mxUserStyle('deep', "@-webkit-keyframes grow {\n  0%   { font-size: 22px; }\n  100% { font-size: 1000px; }\n}\n\n.header_list.admin .icon {\n  -webkit-animation: grow 120s ease-in 0s infinite alternate;\n}");

mxUserStyle('deb', "@-webkit-keyframes rotx {\n  0%   { -webkit-transform: rotateX(-7deg); }\n  100% { -webkit-transform: rotateX(7deg); }\n}\n\n.left_cont {\n  -webkit-perspective: 1000;\n}\n\n.graph_module_container {\n  -webkit-transform-origin: left top;\n  -webkit-animation: rotx 4s ease-in-out 0s infinite alternate;\n}");

mxUserStyle('max', "body {\n  -webkit-filter: grayscale(100%);\n}\n\n#-webkit-web-inspector {\n  -webkit-transform: rotate(180deg);\n}");

mxUserStyle('mike', "@-webkit-keyframes rotx {\n  0%   { -webkit-transform: rotateX(0deg); }\n  100% { -webkit-transform: rotateX(360deg); }\n}\n\n.left_cont {\n  -webkit-perspective: 1000;\n}\n\n.graph_module_container {\n  -webkit-animation: rotx 30s linear 0s infinite alternate;\n}");

mxUserStyle('alexa', "body {\n  -webkit-filter: grayscale(100%);\n}");

mxUserStyle('cory', "@-webkit-keyframes grow {\n  0%   { letter-spacing: 0px; }\n  100% { letter-spacing: 5px; }\n}\n\nbody {\n  -webkit-animation: grow 5s linear 0s infinite alternate;\n}\n\n#-webkit-web-inspector {\n  -webkit-transform: rotate(180deg);\n}");

mxUserStyle('mandeep', "@-webkit-keyframes grow {\n  0%   { -webkit-transform: scale(1, 1); }\n  100% { -webkit-transform: scale(30, 30); }\n}\n\n.header .left .logo {\n  -webkit-animation: grow 100s ease-in 0s infinite alternate;\n  -webkit-transform-origin: top left;\n}");

mxUserStyle('steve', "@-webkit-keyframes byebye {\n  0%   { -webkit-transform: scale(1, 1); }\n  100% { -webkit-transform: scale(0.15, 0.15); }\n}\n\nbody {\n  -webkit-animation: byebye 40s ease-in 0s infinite alternate;\n}");
